### ISSUE TITLE
Mauvaise gestion des points

### ISSUE THREAD

**Issue by QuentinCastillo** [CeriAvignon/Projet2015#19]
La gestion des scores est différente du jeu original :
    - Le nombre de points à atteindre doit être différent selon le nombre de joueurs.
2 joueurs -> 10points  à atteindre { Par round : 0 point pour le 2nd, 1 point pour le 1er }
3 joueurs -> 20points  à atteindre  { 0, 1, 2 }
4 joueurs -> 30points  à atteindre { 0, 1, 2, 3 }
5 joueurs -> 40points  à atteindre { 0, 1, 2, 3, 4 }
6 joueurs -> 50points  à atteindre { 0, 1, 2, 3, 4, 5 }

**Comment by vlabatut** [comment]
Et du coup, le nombre de points à atteindre ne change-t-il pas aussi ? Sinon, atteindre 35 points en marquant un maximum de 2 pts par manche, ça me parait un peu long...

**Comment by LatifAlexandre** [comment]
Bonjour, un maximum de 2 points c'est dans le cas ou le nombre de points à atteindre = 20.
Donc il faudra minimum 10 manches pour qu'une partie puisse être finie.

**Comment by CharlieBrugvin** [comment]
De plus, il me semble que si l'on fait la moyenne des points gagné par manches, cela ne représente rien de concret, étant donné que les points gagné par manches varient en fonction du nombre de joueur. Gagner 1 points signifie que l'on est premier dans une partie a 2, mais avant-dernier dans une partie a 6..

**Comment by vlabatut** [comment]
@LatifAlexandre au temps pour moi, j'avais survolé le post initial
@CharlieBrugvin tout à fait. à moins de normaliser par rapport au nombre total de points marquable.

**Comment by vlabatut** [comment]
@QuentinCastillo tu es sûr de tes valeurs ? quand on fait une partie rapide sur curve fever, on est 6 et c'est en 35 points (pas 50)

**Comment by QuentinCastillo** [comment]
Pour les parties rapides, c'est en effet 35, mais c'est une fonctionnalité qui a été ajoutée récemment au jeu de base. Les parties normales sont bien de la forme que j'ai décrite ci-dessus.

**Comment by vlabatut** [comment]
ok, j'ai fait la correction

**Comment by vlabatut** [comment]
pour info, il suffit d'éditer la classe qui contient toutes les constantes du jeu, au cas où vous auriez besoin de changer ça lors du débuggage.
