### ISSUE TITLE
Les bordures au début d'une manche

### ISSUE THREAD

**Issue by LatifAlexandre** [CeriAvignon/Projet2015#20]
Bonjour, dans le jeu original, les joueurs ont le droit de sortir des bords du jeu (sans re-entrer de l'autre côté) pour éviter que quelqu'un meurt dès le début d'une manche parce qu'il pop à côté d'un bord.
Vu la compléxité de cette tâche, peut être faudra juste se contenter d'activer le mode "fly" pour 2-3 secondes au début d'une manche.

**Comment by vlabatut** [comment]
Oui, on a laissé ça comme ça volontairement : on estimait que ça ne changeait rien au jeu, et que ça ne valait pas la peine d'y passer du temps. Note que les joueurs ne peuvent pas apparaître initialement trop près du bord, donc en pratique je ne pense pas que ça pose de problème. 
On ne corrigera pas ça, à moins que quelqu'un montre que ça pose un problème significatif en termes de jouabilité. 
Mais merci quand même de l'avoir signalé !
