### ISSUE TITLE
Commencer une pratie sans définir les boutons de direction.

### ISSUE THREAD

**Issue by LatifAlexandre** [CeriAvignon/Projet2015#21]
Bonjour, quand on choisi les boutons de directions on a le droit de ne rien choisir (dans ce cas on a le symbol "**?**"). Je sais que ce n'est pas un vrai issue mais je pense qu'il faut juste rajouter une condition pour dire qu'on ne peut pas commencer une partie si les boutons ne sont pas définis.

**Comment by vlabatut** [comment]
Il me semble qu'initialement, on faisait ce test, donc ça doit être un bug simple à corriger. je vais voir ça.

**Comment by vlabatut** [comment]
@LatifAlexandre après vérification, je pense que tu dois utiliser une ancienne version du jeu, car ça fait un moment que les touches sont initialisées : il n'y a plus de "?"

**Comment by LatifAlexandre** [comment]
ok parfait merci!

**Comment by LatifAlexandre** [comment]
Bonjour Monsieur, après vérification : on peut toujours commencer une partie sans définir les boutons (appuyer une fois sur le bouton rouge ou bleu et laisser vide).
![capture du 2016-03-16 15 20 48](https://cloud.githubusercontent.com/assets/14905599/13815409/b8bb1b18-eb8a-11e5-9ebd-ff543c4fe780.png)

**Comment by vlabatut** [comment]
Tant que tu ne définis pas une nouvelle touche, l'ancienne n'est pas remplacée. Comme il y a forcément une touche par défaut (c'est ce que je voulais dire en disant qu'il n'y avait plus de "?"), alors quand tu commences la partie chaque joueur a forcément des touches assignées. Je viens de tester avec exactement le cas que tu as capturé ci-dessus, et on peut effectivement contrôler les serpents avec les touches, tout à fait normalement.
