### ISSUE TITLE
getIp() retourne NULL

### ISSUE THREAD

**Issue by nathan30** [CeriAvignon/Projet2015#24]
Bonjour,

Est-ce normal que les fonctions getIp() de ServerCommunicationImpl() et ClientCommunicationImpl()
renvoi NULL lorsque qu'on les utilise ? 

Exemple de notre implementation pour la communication PHP : 

`public void sendIP()throws IOException {
        URL url = new URL("https://pedago02a.univ-avignon.fr/~uapv1402577/server/server.php");
        String result = "";
        ServerCommunicationImpl server = new ServerCommunicationImpl();
        System.out.println(server.getIp());
        String data = "infos=" + URLEncoder.encode(server.getIp()+"|4", "UTF-8");
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();`

le SYSO nous renvoi un NULL

Merci d'avance

**Comment by vlabatut** [comment]
L'IP stockée dans `ClientCommunication` est celle du serveur auquel tu veux te connecter. Elle est à spécifiée avec setIp, sinon elle sera nulle, ce qui est normal.

Celle stockée dans `ServerCommunication` est normalement celle de la machine, et ne doit pas être nulle. Cependant, une machine possède de nombreuses IP différentes, et non pas une seule (par ex. 127.0.0.1, et d'autres). Donc pour déterminer celle dont on a besoin, on filtre les IP disponibles en fonction de leurs première valeurs : 192.168..... ou 10.104....., par exemple. On a pris des valeurs qui marchent sur le réseau de l'université. Si tu testes ça ailleurs, c'est possible qu'aucune IP ne commence par l'un des préfixes spécifiés. Il te suffit alors de modifier `ServerCommunicationImpl.getIp` pour y inclure un préfixe compatible avec ton IP.

**Comment by nathan30** [comment]
Le problème c'est que si jamais l'adresse en 192.168 est utilisé ca sera seulement une partie en locale..

**Comment by vlabatut** [comment]
Tu peux vouloir avoir le client et le serveur sur la même machine, pour faire des tests. (ou sur un réseau privé)

**Comment by vlabatut** [comment]
J'ai simplifié le filtrage des IP dans la toute dernière version : il suffit de rajouter un préfixe dans `Constants.IP_PREFIXES`
