### ISSUE TITLE
Nb joueurs locaux reset avec Retour

### ISSUE THREAD

**Issue by nathan30** [CeriAvignon/Projet2015#28]
Quand on choisi un nombre de joueurs locaux supérieur à 1, que l'on clique sur suivant pour accéder a à la selection des joueurs distants puis que l'on clique sur "retour" pour revenir à la selection des joueurs locaux le combobox est revenu à 1 (mais sa valeur est égale au nombre choisi avant), et donc seul le profil du créateur de la partie est présent

**Comment by vlabatut** [comment]
La version que tu as utilisée est-elle à jour ? Car je viens de tester la manipulation, et je n'ai pas rencontré le problème décrit. 

Déjà, je suppose que tu parles de la création d'une partie réseau ? Quand je reviens à la sélection des joueurs locaux, après à voir fait ce que tu décris, j'ai un seul joueur sélectionné et le combobox affiche bien la valeur 1.

**Comment by nathan30** [comment]
Le problème apparait quand on selectionne par exemple 3 joueurs locaux, on clique sur suivant puis sur retour pour revenir sur la selection des joueurs locaux et là on verra qu'il n'y à qu'un seul joueur local au lieu des 3 choisis précedemment

**Comment by vlabatut** [comment]
Ok, donc ce n'est pas tout à fait ce qui était décrit dans ton message original, où le problème semblait être une différence entre le nombre de joueurs affichés dans la combobox et le nombre de joueurs effectivement sélectionnés et affichés.

Quoi qu'il en soit, ce n'est pas un bug mais bien un parti-pris. Si tu regardes le code source, tu verras que pour ce panel comme pour les autres, les objets concernés (ici : le nombre de joueurs sélectionnés) sont réinitialisés à chaque affichage. C'est sûr que ça serait mieux de restaurer les réglages précédents, mais on n'a pas jugé ça absolument nécessaire. Rien ne vous empêche (vous=les groupes) d'y remédier, cependant.

**Comment by nathan30** [comment]
Le problème est que la valeur de la combobox elle n'est pas réinitialisée. Et même si elle affiche "1" après avoir fait la manip que j'ai décrite dans mon précédent commentaire, sa valeur restera de 3

**Comment by vlabatut** [comment]
Il faudra que tu me montres ça lors de la prochaine séance. Je ne parviens pas à reproduire ce bug, sur mes machines ça marche correctement.
