### ISSUE TITLE
rapports

### ISSUE THREAD

**Issue by FDEMOL** [CeriAvignon/Projet2015#3]

**Comment by soufianeess** [comment]
Bonjour monsieur
Je suis soufiane essaboni l3 informatique td3 groupe 20 moteur reseau .
La premi�re s�ance dans laquelle vous avez d�fini les bin�mes j'�tais absent du coup ma coll�gue m'as choisie comme son bin�me � mon retour j'ai constat� �a du coup je voulais pas dire non par contre l� on est en dispute depuis l'instant t0 du notre travail.
Alors je demande si vous pouvez me changer le groupe (bin�me) si c'est possible. si non je pr�f�re  travailler seule que de rester comme �a au moins je serais le seule responsable de mon travail et ma note (elle "ibtissam benachour" est aussi d'accord de la s�paration du bin�me ).
Merci cordialement .
