### ISSUE TITLE
Déconnexions pas détectées

### ISSUE THREAD

**Issue by vlabatut** [CeriAvignon/Projet2015#31]
Avec le moteur réseau Kryonet, le fait qu'un client se déconnecte en pleine partie n'est pas détecté par le serveur. Si cela arrive pendant une manche, le serpent devrait devenir gris (comme avec le MR socket). Si ça se produit entre deux manches, il y a un blocage du serveur due à un deadlock (la manche suivante ne commence jamais après la fermeture du menu modal).
@ZacharieALES

**Comment by vlabatut** [comment]
Un problème apparaît aussi dans le loby, quand un client se retire d'une partie pas encore commencée. C'est probablement du à la même chose (mais peut-être pas).

**Comment by ZacharieALES** [comment]
De mon coté, la fermeture dans la loby se passe correctement.
Lorsqu'un client quitte pendant la partie, sa trace deviens gris (par
contre il continue tout droit et ira également tout droit aux manches
suivantes).

Cela se produit peut être uniquement sur windows. Je passerai voir le
comportement de ton coté.

**Comment by BelghitiAlaoui-Hicham** [comment]
Je confirme ce que Mr.Ales a dit

**Comment by vlabatut** [comment]
@BelghitiAlaoui-Hicham attention à bien utiliser le mode `KRYONET` et non pas `SOCKET` dans le fichier de configuration.
