### ISSUE TITLE
Pas de mise à jour de la limite des scores après une égalité (11/11) (19/19)...etc.

### ISSUE THREAD

**Issue by LatifAlexandre** [CeriAvignon/Projet2015#32]
Bonjour, la limite des scores, dans le jeu original, s'augmente de 1 quand au moins 2 des joueurs est à 1 point du score à atteindre (e.g : les 2 joueurs sont à 9 points , la limite est à 10, alors la limite s'augmente de 1).

**Comment by vlabatut** [comment]
normalement, c'est maintenant corrigé. à tester !
