### ISSUE TITLE
Problème de ressources

### ISSUE THREAD

**Issue by K-Lovelace** [CeriAvignon/Projet2015#33]
Lorsqu'on joue longtemps contre une ou plusieurs IA (à peu près une dizaine de rounds) les IA arrêtent de fonctionner. La fonction processDirection n'est plus du tout appelée.

**Comment by vlabatut** [comment]
Est-ce que ça se produit sur ton projet fusionné avec celui du dépot officiel, ou bien sur la version officielle (pure) ? (je pose la question car j'ai déjà vu aujourd'hui plusieurs bugs dûs à la fusion entre votre code et le nôtre)

**Comment by K-Lovelace** [comment]
Cela se produit sur une version reprise depuis la branche iaapi du dépot officiel. J'utilise des agents avoidcloserwall

**Comment by vlabatut** [comment]
Je ne parviens pas à reproduire le bug. Faut il obligatoirement un joueur humain ?

Edit : même avec un joueur humain, le bug n'apparaît pas chez moi. La prochaine fois que vous le rencontrez, il faudrait voir quelles conditions aboutissent à son apparition.

**Comment by vlabatut** [comment]
J'ai tenté de reproduire le bug avec 6 agents, comme vous me l'avez indiqué lors de la dernière séance, mais sans succès. Le mieux serait de me montrer directement comment vous provoquez le bug, lors de la prochaine séance.

**Comment by K-Lovelace** [comment]
Le plus simple est de jouer contre un agent et de faire durer chaque manche le plus longtemps possible. Normalement au bout de quelques manches l'agent ne fait plus rien.

**Comment by vlabatut** [comment]
Même en faisant ça, le bug ne se produit pas sur ma machine. C'est peut être une question de mémoire : essayez en allouant plus de mémoire à la JVM (cf. http://stackoverflow.com/questions/4175188/setting-memory-of-java-programs-that-runs-from-eclipse) et dites-moi ce que ça donne.

**Comment by vlabatut** [comment]
Il semblerait que ce ne soit pas un problème de mémoire, en fin de compte. J'ai fait une modification du gestionnaire d'agents, il semblerait que le problème n'apparaisse plus désormais (d'après les tests effectués en séance, du moins).
