### ISSUE TITLE
problème collision

### ISSUE THREAD

**Issue by CharlieBrugvin** [CeriAvignon/Projet2015#34]
Lorsque je baisse le délai entre 2 maj physiques, les snakes font naturellmement un plus grand pas entre deux itérations. Mais j'ai l'impression que si le pas est trop grand, les snakes peuvent 'sauter' par dessur un obstacle. Par exemple, elles arrivent contre un bord, et réaparaissent de l'autre côté (sans avoir le mode fly bien-sûr), en ignorant simplement le bord.

**Comment by vlabatut** [comment]
Oui, c'est dû à la façon dont la mise à jour est faite : on teste s'il y a collision seulement pour la position occupée à la fin de la mise à jour (et pas pour les positions intermédiaires). Ca permet d'alléger les calculs. A priori, ça n'est pas gênant, car la distance parcourue est faible... si on ne modifie pas le délai dont tu parles, bien sûr.

**Comment by CharlieBrugvin** [comment]
Dans le cadre d'une IA en BackTracking, cela peut être interssant d'agrandir ce délai. Mais je vais essayer de contourner le problème
