### ISSUE TITLE
Item inversion des commandes

### ISSUE THREAD

**Issue by vlabatut** [CeriAvignon/Projet2015#35]
Quand on ramasse un nombre pair d'item d'inversion des commande, les effets devraient s'annuler. Ce qui n'est pas le cas actuellement.

**Comment by QuentinCastillo** [comment]
Bonjour, 
je ne suis pas sur que ça soit le cas, il me semble que dans le jeu original, prendre plusieurs fois l'inversion ne fait que rafraîchir la durée (contrairement aux slow/speed qui se cumulent).

**Comment by vlabatut** [comment]
Ah oui, c'est possible... cependant, je ne pense pas avoir le temps de corriger, donc a priori ça va rester comme ça. L'effet est très marginal, donc je ne pense pas que ça soit très grave. Du point de vue des agents, ça ne change rien car le traitement de cet item est trivial pour eux.
