### ISSUE TITLE
Mauvaise taille de fenêtre

### ISSUE THREAD

**Issue by Epsilonn2** [CeriAvignon/Projet2015#5]
On ne peut pas cliquer sur le bouton pour lancer la partie car la fenetre est trop grande (sur un écran d'ordi portable)

**Comment by vlabatut** [comment]
On a repris la taille de 800x800 pour l'aire de jeu, qui avait été proposée lors du S1. On peut modifier cette taille, mais ça implique de revoir de nombreux autres paramètres du jeu, tels que les vitesses de déplacement. On va voir ça.

**Comment by vlabatut** [comment]
J'ai fait au plus simple : il est maintenant possible de changer la taille de l'aire de jeu dans le fichier de configuration (res/settings/settings.txt). Les deux dernières valeurs expriment la largeur et la hauteur de l'aire de jeu, en pixels. Les vitesses et les autres paramètres du jeu ne sont pas touchés.
