### ISSUE TITLE
Item passe-muraille

### ISSUE THREAD

**Issue by QuentinCastillo** [CeriAvignon/Projet2015#6]
- L'item permettant de traverser les murs est supposé avoir un timer qui apparaît sur tous les snakes.

**Comment by vlabatut** [comment]
Pourrais-tu éditer ta description de manière à ne garder que le premier point, et mettre les deux autres dans deux issues différentes, stp?

**Comment by vlabatut** [comment]
c'était volontaire, mais effectivement ça ne respecte pas l'original

**Comment by vlabatut** [comment]
Corrigé
